### ISSUE TITLE
Import failure on Globals

### ISSUE THREAD

**Issue by tian2992** [Nexedi/dream#4]
When trying to run one of the samples, (e.g. /dream/simulation/Examples/ParallelServers1.py) breaks on import of Globals

```
import Globals
  File "/home/tian/devel/dream/venv/lib/python2.7/site-packages/dream-0.0.1-py2.7.egg/dream/simulation/Globals.py", line 29, in <module>
    from Machine import Machine
ImportError: cannot import name Machine
```

**Comment by jerome-nexedi** [comment]
I can reproduce here when running the examples after installing using `pip install -e .` from the root directory ( after disabling the complex dependencies that are only available in the full SlapOS installation).

To me, it seem to come from a circular dependency, probably just in the examples because the test suite runs fine.

This patch seem to fix ( `Globals` is already imported later anyway )
```diff
diff --git a/dream/simulation/SkilledOperatorRouter.py b/dream/simulation/SkilledOperatorRouter.py
index 9106d83..43c7226 100644
--- a/dream/simulation/SkilledOperatorRouter.py
+++ b/dream/simulation/SkilledOperatorRouter.py
@@ -29,7 +29,6 @@ import simpy
 
 from OperatorRouter import Router
 from opAss_LPmethod import opAss_LP
-import Globals
 
 # ===========================================================================
 #               Class that handles the Operator Behavior
```
@GeorgiosDagkakis  ?

**Comment by tian2992** [comment]
I changed the import on globals as
```
-from Machine import Machine
+import Machine
```
And it imports and works properly.

**Comment by tian2992** [comment]
Been keeping track of my changes on
https://github.com/Nexedi/dream/compare/master...tian2992:cleanup?expand=1

**Comment by jerome-nexedi** [comment]
We are not really using github for issues / merge requests, this github is just a mirror. If you like to discuss further, I would suggest you file issue on https://lab.nexedi.com/nexedi/dream/

We are disabling issues on github now, thanks.
